# acorn2sfd
# Autogenerated from man page /usr/share/man/man1/acorn2sfd.1.gz
complete -c acorn2sfd -l help -d 'Provide a description with a list of available options'
complete -c acorn2sfd -l includestrokes -d 'Set a flag to include strokes'
complete -c acorn2sfd -l version -d 'Display the current version'

