# aseqsend
# Autogenerated from man page /usr/share/man/man1/aseqsend.1.gz
complete -c aseqsend -s h -d 'Prints a list of options'
complete -c aseqsend -s V -d 'Prints the current version'
complete -c aseqsend -s l -d 'Prints a list of possible output ports'
complete -c aseqsend -s v -d 'Prints number of bytes actually sent'
complete -c aseqsend -s p -d 'Target port by number or name'
complete -c aseqsend -s s -d 'Send raw binary data from given file name'
complete -c aseqsend -s i -d 'Interval between SysEx messages in miliseconds A client can be specified by i…'

