# aseqdump
# Autogenerated from man page /usr/share/man/man1/aseqdump.1.gz
complete -c aseqdump -s h -l help -d 'Prints a list of options'
complete -c aseqdump -s V -l version -d 'Prints the current version'
complete -c aseqdump -s l -l list -d 'Prints a list of possible input ports'
complete -c aseqdump -s u -l ump -d 'Sets the client MIDI version.  0 is for legacy mode, 1 is UMP MIDI 1'
complete -c aseqdump -s r -l raw -d 'Suppress the automatic conversion of events among UMP and legacy clients'
complete -c aseqdump -s R -l raw-view -d 'Shows the raw values as is'
complete -c aseqdump -s N -l normalized-view -d 'Shows the normalized values to be aligned with MIDI 1. 0'
complete -c aseqdump -s P -l percent-view -d 'Shows the values in percentage'
complete -c aseqdump -s p -l port -d 'Sets the sequencer port(s) from which events are received'

