# cert-to-efi-hash-list
# Autogenerated from man page /usr/share/man/man1/cert-to-efi-hash-list.1.gz
complete -c cert-to-efi-hash-list -s g -d 'Use <guid> as the owner of the signature'
complete -c cert-to-efi-hash-list -s s -d 'Use SHA<hash> hash algorithm (256, 384, 512)'
complete -c cert-to-efi-hash-list -s t -d 'Time of Revocation for hash signature'

