# efi-readvar
# Autogenerated from man page /usr/share/man/man1/efi-readvar.1.gz
complete -c efi-readvar -s v -d 'list only the contents of <var>'
complete -c efi-readvar -s s -d 'list only a given signature list (and optionally'
complete -c efi-readvar -s o -d 'output the requested signature lists to <file> EXAMPLES'

