# env_parallel
# Autogenerated from man page /usr/share/man/man1/env_parallel.1.gz
complete -c env_parallel -l end-session -d 'X Item "--end-session" Undo last --session'
complete -c env_parallel -l record-env -d 'X Item "--record-env" Record all names currently defined to be ignored every …'
complete -c env_parallel -l session
complete -c env_parallel -l env -d 'given name.  Multiple --envs can be given'

