# expac
# Autogenerated from man page /usr/share/man/man1/expac.1.gz
complete -c expac -s Q -l query -d 'X Item "-Q, --query" Search the local database for provided targets'
complete -c expac -s S -l sync -d 'X Item "-S, --sync" Search the sync databases for provided targets'
complete -c expac -s s -l search -d 'X Item "-s, --search" Search for packages matching the strings specified by t…'
complete -c expac -s g -l group -d 'X Item "-g, --group" Return packages matching the specified targets as packag…'
complete -c expac -l config -d 'X Item "--config <file>" Read from file for alpm initialization instead of /e…'
complete -c expac -s H -l humansize -d 'X Item "-H, --humansize <size>" Format package sizes in SI units according to…'
complete -c expac -s 1 -l readone -d 'X Item "-1, --readone" Stop searching after the first result'
complete -c expac -s d -l delim -d 'X Item "-d, --delim <string>" Separate each package with the specified string'
complete -c expac -s l -l listdelim -d 'X Item "-l, --listdelim <string>" Separate each list item with the specified …'
complete -c expac -s p -l file -d 'X Item "-p, --file" Interpret targets as paths to local files'
complete -c expac -s t -l timefmt -d 'X Item "-t, --timefmt <format>" Output time described by the specified format'
complete -c expac -s v -l verbose -d 'X Item "-v, --verbose" Output more'
complete -c expac -s V -l version -d 'X Item "-V, --version" Display version information and quit'
complete -c expac -o sync -d OPTIONS
complete -c expac -s h -l help

