# fi_info
# Autogenerated from man page /usr/share/man/man1/fi_info.1.gz
complete -c fi_info -s n -d 'Node name or address used to filter interfaces'
complete -c fi_info -s P -d 'Port number used to filter interfaces'
complete -c fi_info -s c -d 'Pipe separated list of capabilities used to filter interfaces'
complete -c fi_info -s m -d 'Pipe separated list of modes used to filter interfaces'
complete -c fi_info -s t -d 'Specifies the type of fabric interface communication desired'
complete -c fi_info -s a -d 'Filter fabric interfaces by their address format'
complete -c fi_info -s p -d 'Filter fabric interfaces by the provider implementation'
complete -c fi_info -s d -d 'Filter interfaces to only those with the given domain name'
complete -c fi_info -s f -d 'Filter interfaces to only those with the given fabric name.  Discovery'
complete -c fi_info -s e -d 'List libfabric related environment variables which can be used to enable extr…'
complete -c fi_info -s l -d 'List available libfabric providers'
complete -c fi_info -s v -d 'By default, fi_info will display a summary of each of the interfaces discover…'
complete -c fi_info -s g -d '$ '

