# fi_pingpong
# Autogenerated from man page /usr/share/man/man1/fi_pingpong.1.gz
complete -c fi_pingpong -s B -d 'The non-default source port number of the control socket'
complete -c fi_pingpong -s P -d 'The non-default destination port number of the control socket'
complete -c fi_pingpong -s p -d 'The name of the underlying fabric provider (e. g. , sockets, psm3, usnic, etc'
complete -c fi_pingpong -s e -d 'The type of endpoint to be used for data messaging between the two processes'
complete -c fi_pingpong -s d -d 'The name of the specific domain to be used.  Test Options'
complete -c fi_pingpong -s I -d 'The number of iterations of the test will run'
complete -c fi_pingpong -s S -d 'The specific size of the message in bytes the test will use or `all\' to run a…'
complete -c fi_pingpong -s c -d 'Activate data integrity checks at the receiver (note: this will degrade perfo…'
complete -c fi_pingpong -s v -d 'Activate output debugging (warning: highly verbose)'
complete -c fi_pingpong -s h -d 'Displays help output for the pingpong test'

