# getent
# Autogenerated from man page /usr/share/man/man1/getent.1.gz
complete -c getent -l 'service\\~' -d 'TQ  -s\\~ service '
complete -c getent -l no-idn -d 'TQ  -i '
complete -c getent -l help -d 'TQ  -? Print a usage summary and exit'
complete -c getent -l usage -d 'Print a short usage summary and exit'
complete -c getent -l service
complete -c getent -s s
complete -c getent -s i
complete -c getent -s '?' -d 'Print a usage summary and exit'
complete -c getent -l version
complete -c getent -s V -d 'Print the version number, license, and disclaimer of warranty for getent '

