# i686-w64-mingw32-elfedit
# Autogenerated from man page /usr/share/man/man1/i686-w64-mingw32-elfedit.1.gz
complete -c i686-w64-mingw32-elfedit -l input-mach -d 'X Item "--input-mach=machine" Set the matching input ELF machine type to mach…'
complete -c i686-w64-mingw32-elfedit -l output-mach -d 'X Item "--output-mach=machine" Change the ELF machine type in the ELF header …'
complete -c i686-w64-mingw32-elfedit -l input-type -d 'X Item "--input-type=type" Set the matching input ELF file type to type'
complete -c i686-w64-mingw32-elfedit -l output-type -d 'X Item "--output-type=type" Change the ELF file type in the ELF header to type'
complete -c i686-w64-mingw32-elfedit -l input-osabi -d 'X Item "--input-osabi=osabi" Set the matching input ELF file OSABI to osabi'
complete -c i686-w64-mingw32-elfedit -l output-osabi -d 'X Item "--output-osabi=osabi" Change the ELF OSABI in the ELF header to osabi'
complete -c i686-w64-mingw32-elfedit -l input-abiversion -d 'X Item "--input-abiversion=version" Set the matching input ELF file ABIVERSIO…'
complete -c i686-w64-mingw32-elfedit -l output-abiversion -d 'X Item "--output-abiversion=version" Change the ELF ABIVERSION in the ELF hea…'
complete -c i686-w64-mingw32-elfedit -l enable-x86-feature -d 'X Item "--enable-x86-feature=feature" Set the feature bit in program property…'
complete -c i686-w64-mingw32-elfedit -l disable-x86-feature -d 'X Item "--disable-x86-feature=feature" Clear the feature bit in program prope…'
complete -c i686-w64-mingw32-elfedit -s v -d 'X Item "-v"'
complete -c i686-w64-mingw32-elfedit -l version -d 'X Item "--version" . PD Display the version number of elfedit'
complete -c i686-w64-mingw32-elfedit -s h -d 'X Item "-h"'
complete -c i686-w64-mingw32-elfedit -l help -d 'X Item "--help" . PD Display the command-line options understood by elfedit'

