# iconv
# Autogenerated from man page /usr/share/man/man1/iconv.1.gz
complete -c iconv -l from-code -d 'TQ  -f\\~ from-encoding Use  from-encoding for input characters'
complete -c iconv -l to-code -d 'TQ  -t\\~ to-encoding Use  to-encoding for output characters'
complete -c iconv -l list -d 'TQ  -l List all known character set encodings'
complete -c iconv -s c -d 'Silently discard characters that cannot be converted instead of terminating w…'
complete -c iconv -l output -d 'TQ  -o\\~ outputfile Use  outputfile for output'
complete -c iconv -l silent -d 'TQ  -s This option is ignored; it is provided only for compatibility'
complete -c iconv -l verbose -d 'Print progress information on standard error when processing multiple files'
complete -c iconv -l help -d 'TQ  -? Print a usage summary and exit'
complete -c iconv -l usage -d 'Print a short usage summary and exit'
complete -c iconv -s f -d 'Use from-encoding for input characters'
complete -c iconv -s t -d 'Use to-encoding for output characters'
complete -c iconv -s l -d 'List all known character set encodings'
complete -c iconv -s o -d 'Use outputfile for output'
complete -c iconv -s s -d 'This option is ignored; it is provided only for compatibility'
complete -c iconv -s '?' -d 'Print a usage summary and exit'
complete -c iconv -l version
complete -c iconv -s V -d 'Print the version number, license, and disclaimer of warranty for iconv '

