# iconvconfig
# Autogenerated from man page /usr/share/man/man8/iconvconfig.8.gz
complete -c iconvconfig -l nostdlib -d 'Do not search the system default gconv directory, only the directories provid…'
complete -c iconvconfig -l output -d 'TQ  -o\\~ outputfile Use  outputfile for output instead of the system default …'
complete -c iconvconfig -l prefix -d 'Set the prefix to be prepended to the system pathnames.  See FILES, below'
complete -c iconvconfig -l help -d 'TQ  -? Print a usage summary and exit'
complete -c iconvconfig -l usage -d 'Print a short usage summary and exit'
complete -c iconvconfig -s o -d 'Use outputfile for output instead of the system default cache location'
complete -c iconvconfig -s '?' -d 'Print a usage summary and exit'
complete -c iconvconfig -l version
complete -c iconvconfig -s V -d 'Print the version number, license, and disclaimer of warranty for iconv '

