# ldd
# Autogenerated from man page /usr/share/man/man1/ldd.1.gz
complete -c ldd -l version -d 'Print the version number of  ldd '
complete -c ldd -l verbose -d 'TQ  -v Print all information, including, for example, symbol versioning infor…'
complete -c ldd -l unused -d 'TQ  -u Print unused direct dependencies.  (Since glibc 2. 3. 4. )'
complete -c ldd -l data-relocs -d 'TQ  -d Perform relocations and report any missing objects (ELF only)'
complete -c ldd -l function-relocs -d 'TQ  -r Perform relocations for both data objects and functions, and report an…'
complete -c ldd -s v -d 'Print all information, including, for example, symbol versioning information'
complete -c ldd -s u -d 'Print unused direct dependencies.  (Since glibc 2. 3. 4. )'
complete -c ldd -s d -d 'Perform relocations and report any missing objects (ELF only)'
complete -c ldd -s r -d 'Perform relocations for both data objects and functions, and report any missi…'
complete -c ldd -l help -d 'Usage information'

