# libmikmod-config
# Autogenerated from man page /usr/share/man/man1/libmikmod-config.1.gz
complete -c libmikmod-config -l version -d 'Print the currently installed version of libmikmod on the standard output'
complete -c libmikmod-config -l libs -d 'Print the linker flags that are necessary to link a libmikmod program'
complete -c libmikmod-config -l ldadd -d 'Print the extra linker flags that are necessary to link a libmikmod program i…'
complete -c libmikmod-config -l cflags -d 'Print the compiler flags that are necessary to compile a libmikmod program'
complete -c libmikmod-config -l prefix -d 'If specified, use PREFIX instead of the installation prefix that libmikmod wa…'
complete -c libmikmod-config -l exec-prefix -d 'If specified, use PREFIX instead of the installation exec prefix that libmikm…'

