# llvm-bcanalyzer
# Autogenerated from man page /usr/share/man/man1/llvm-bcanalyzer.1.gz
complete -c llvm-bcanalyzer -l dump -d 'Causes llvm-bcanalyzer to dump the bitcode in a human readable format'
complete -c llvm-bcanalyzer -l help -d 'Print a summary of command line options'

