# llvm-reduce
# Autogenerated from man page /usr/share/man/man1/llvm-reduce.1.gz
complete -c llvm-reduce -l help -d 'Display available options (--help-hidden for more)'
complete -c llvm-reduce -l abort-on-invalid-reduction -d 'Abort if any reduction results in invalid IR'
complete -c llvm-reduce -l in-place -d 'WARNING: This option will replace your input file with the reduced version!'
complete -c llvm-reduce -l ir-passes -d 'A textual description of the pass pipeline, same as what\'s passed to opt -pas…'
complete -c llvm-reduce -s j -d 'Maximum number of threads to use to process chunks'
complete -c llvm-reduce -l max-pass-iterations -d 'Maximum number of times to run the full set of delta passes (default=5)'
complete -c llvm-reduce -l mtriple -d 'Set the target triple'
complete -c llvm-reduce -l preserve-debug-environment -d 'Don\'t disable features used for crash debugging (crash reports, llvm-symboliz…'
complete -c llvm-reduce -l print-delta-passes -d 'Print list of delta passes, passable to --delta-passes as a comma separated l…'
complete -c llvm-reduce -l skip-delta-passes -d 'Delta passes to not run, separated by commas'
complete -c llvm-reduce -l starting-granularity-level -d 'Number of times to divide chunks prior to first test'
complete -c llvm-reduce -l test -d 'Name of the interesting-ness test to be run'
complete -c llvm-reduce -l test-arg -d 'Arguments passed onto the interesting-ness test'
complete -c llvm-reduce -l verbose -d 'Print extra debugging information'
complete -c llvm-reduce -l write-tmp-files-as-bitcode -d 'Always write temporary files as bitcode instead of textual IR'
complete -c llvm-reduce -s x -d 'Input language as ir or mir'

