# llvm-opt-report
# Autogenerated from man page /usr/share/man/man1/llvm-opt-report.1.gz
complete -c llvm-opt-report -l help -d 'Display available options'
complete -c llvm-opt-report -l version -d 'Display the version of this program'
complete -c llvm-opt-report -l format -d 'The format of the optimization record file'
complete -c llvm-opt-report -l no-demangle -d 'Do not demangle function names'
complete -c llvm-opt-report -s o -d 'Output file'
complete -c llvm-opt-report -s r -d 'Root for relative input paths'
complete -c llvm-opt-report -s s -d 'Do not include vectorization factors, etc'

