# llvm-remarkutil
# Autogenerated from man page /usr/share/man/man1/llvm-remarkutil.1.gz
complete -c llvm-remarkutil -l parser -d 'Select the type of input remark parser.  Required'
complete -c llvm-remarkutil -l report-style -d 'Output style.  * human: Human-readable textual report.  Default option'
complete -c llvm-remarkutil -l pretty -d 'Pretty-print JSON output.  Optional'
complete -c llvm-remarkutil -s o -d 'Output file for the report.  Outputs to stdout by default'
complete -c llvm-remarkutil -l -----
complete -c llvm-remarkutil -l 'count-by<value>'
complete -c llvm-remarkutil -l group-by
complete -c llvm-remarkutil -l args
complete -c llvm-remarkutil -l rargs
complete -c llvm-remarkutil -l pass-name
complete -c llvm-remarkutil -l rpass-name
complete -c llvm-remarkutil -l remark-name
complete -c llvm-remarkutil -l rremark-name
complete -c llvm-remarkutil -l filter-arg-by
complete -c llvm-remarkutil -l rfilter-arg-by
complete -c llvm-remarkutil -l remark-type

