# locale
# Autogenerated from man page /usr/share/man/man1/locale.1.gz
complete -c locale -l all-locales -d 'TQ  -a Display a list of all available locales'
complete -c locale -l charmaps -d 'TQ  -m Display the available charmaps (character set description files)'
complete -c locale -l category-name -d 'TQ  -c For a category name argument, write the name of the locale category on…'
complete -c locale -l keyword-name -d 'TQ  -k For each keyword whose value is being displayed, include also the name…'
complete -c locale -l verbose -d 'TQ  -v Display additional information for some command-line option and argume…'
complete -c locale -l help -d 'TQ  -? Display a summary of command-line options and arguments and exit'
complete -c locale -l usage -d 'Display a short usage message and exit'
complete -c locale -s a -d 'or the'
complete -c locale -s m -d 'option (or one of their long-format equivalents) is specified, the behavior i…'
complete -c locale -s v -d 'option causes the LC_IDENTIFICATION metadata about each locale to be included…'
complete -c locale -s c -d 'For a category name argument, write the name of the locale category on a sepa…'
complete -c locale -s k -d option
complete -c locale -s '?' -d 'Display a summary of command-line options and arguments and exit'
complete -c locale -l version
complete -c locale -s V -d 'Display the program version and exit.  FILES'

