# meld
# Autogenerated from man page /usr/share/man/man1/meld.1.gz
complete -c meld -l auto-compare -s a -d 'br Automatically compare all differing files on startup'
complete -c meld -l auto-merge -d 'br Automatically merge files'
complete -c meld -l comparison-file -d 'br Load a saved comparison from a Meld comparison file'
complete -c meld -l diff -d 'br Create a diff tab for the given files or directories'
complete -c meld -l help -s h -d 'br Print application help and usage'
complete -c meld -l label -s L -d 'br Set application window title to <label>'
complete -c meld -l newtab -s n -d 'br Open the comparison as a new tab in an already-running instance'
complete -c meld -l output -s o -d 'br Sets the save path for the middle buffer in a three-pane merge view'
complete -c meld -l unified -s u -d 'br Ignored for compatibility'
complete -c meld -l version

