# mpisync
# Autogenerated from man page /usr/share/man/man1/mpisync.1.gz
complete -c mpisync -s o -l output -d 'to HNP will be written o 2'
complete -c mpisync -s h -l help -d 'ompi_timing_post takes the timing output file as input parameter'

