# ncdump
# Autogenerated from man page /usr/share/man/man1/ncdump.1.gz
complete -c ncdump -s c -d 'Show the values of coordinate variables (1D variables with the same names as …'
complete -c ncdump -s h -d 'Show only the header information in the output, that is, output only the decl…'
complete -c ncdump -s v -d 'The output will include data values for the specified variables, in addition …'
complete -c ncdump -s b -d 'A brief annotation in the form of a CDL comment (text beginning with the char…'
complete -c ncdump -s f -d 'Full annotations in the form of trailing CDL comments (text beginning with th…'
complete -c ncdump -s l -d 'Changes the default maximum line length (80) used in formatting lists of non-…'
complete -c ncdump -s n -d 'CDL requires a name for a netCDF file, for use by ncgen -b in generating a de…'
complete -c ncdump -s p -d 'Specifies default precision (number of significant digits) to use in displayi…'
complete -c ncdump -s k -d 'Show kind of netCDF file the pathname references, one of `classic\', `64-bit o…'
complete -c ncdump -s s -d 'Output special virtual attributes that provide performance-related informatio…'
complete -c ncdump -s t -d 'Controls display of time data, if stored in a variable that uses a udunits co…'
complete -c ncdump -s i -d 'Same as the \'-t\' option, except output time data as date-time strings with IS…'
complete -c ncdump -s g -d 'For netCDF-4 files, the output will include data values only for the specifie…'
complete -c ncdump -s w -d 'For file names that request remote access using DAP URLs, access data with cl…'
complete -c ncdump -s x -d 'Output XML (NcML) instead of CDL.   The NcML does not include data values'
complete -c ncdump -s F -d 'Use _Filter and _Codecs attributes in place of _Fletcher32, _Shuffle, and _De…'

