# ncgen3
# Autogenerated from man page /usr/share/man/man1/ncgen3.1.gz
complete -c ncgen3 -s b -d 'Create a (binary) netCDF file'
complete -c ncgen3 -s c -d 'Generate  C source code that will create a netCDF file matching the netCDF sp…'
complete -c ncgen3 -s f -d 'Generate  Fortran source code that will create a netCDF file matching the net…'
complete -c ncgen3 -s o -d 'Name for the binary netCDF file created'
complete -c ncgen3 -s k -d 'Using -k2 or -k "64-bit offset" specifies that generated file (or program) sh…'
complete -c ncgen3 -s x -d 'Don\'t initialize data with fill values'
complete -c ncgen3 -o '2s	//' -s 2 -d '0123s	// octal 0x7ffs  //hexadecimal Long integer constants are intended for …'
complete -c ncgen3 -o '2.0f' -d '3. 14159265358979f	// will be truncated to less precision 1'
complete -c ncgen3 -o '2.0' -d '3. 141592653589793 1. 0e-20 1. d'

