# ncgen
# Autogenerated from man page /usr/share/man/man1/ncgen.1.gz
complete -c ncgen -s 1 -d 'Alternate method to specify the format. RS . RS'
complete -c ncgen -s b -d 'Create a (binary) netCDF file'
complete -c ncgen -s c -d 'Generate  C source code that will create a netCDF file matching the netCDF sp…'
complete -c ncgen -s d -d 'Same as -D1'
complete -c ncgen -s D -d 'Set the level of debug output'
complete -c ncgen -s f -d 'Generate  FORTRAN 77 source code that will create a netCDF file matching the …'
complete -c ncgen -s h -d 'Output help information'
complete -c ncgen -s H -d 'Output the header only; ignore the data section'
complete -c ncgen -o format_code -d 'The -k flag specifies the format of the file to be created and, by inference,…'
complete -c ncgen -s l -d 'The -l flag specifies the output language to use when generating source code …'
complete -c ncgen -s k
complete -c ncgen -s L
complete -c ncgen -s M -d 'Specify the name for the main function for C, F77, or Java'
complete -c ncgen -s n
complete -c ncgen -s N
complete -c ncgen -s o -d 'Name of the file to pass to calls to "nc_create()"'
complete -c ncgen -s P -d 'Use NC_DISKLESS mode to create the file totally in memory before persisting i…'
complete -c ncgen -s W -d 'Set wholevarsizem where if total number of elements is less than maxwholevars…'
complete -c ncgen -s x -d 'Don\'t initialize data with fill values'
complete -c ncgen -o '2s	//' -s 2 -d '0123s	// octal 0x7ffs  //hexadecimal int integer constants are intended for r…'
complete -c ncgen -o '2ll	//' -d '0123LL	// octal 0x7ffLL  //hexadecimal Floating point constants of type float…'
complete -c ncgen -o '2.0f' -d '3. 14159265358979f	// will be truncated to less precision 1'
complete -c ncgen -o '2.0' -d '3. 141592653589793 1. 0e-20 1'

