# nhlt-dmic-info
# Autogenerated from man page /usr/share/man/man1/nhlt-dmic-info.1.gz
complete -c nhlt-dmic-info -s h -l help -d 'Prints the help information'
complete -c nhlt-dmic-info -s f -l file -d 'Input file with the binary ACPI NHLT table (default is /sys/firmware/acpi/tab…'
complete -c nhlt-dmic-info -s o -l output

