# nvtop
# Autogenerated from man page /usr/share/man/man1/nvtop.1.gz
complete -c nvtop -s d -l delay -d 'Delay between updates, in tenths of seconds (delay * 0. 1s)'
complete -c nvtop -s h -l help -d 'Print the help and exit'
complete -c nvtop -s C -l no-color -d 'Monochrome mode'
complete -c nvtop -s f -l freedom-unit -d 'Use fahrenheit as temperature scale'
complete -c nvtop -s E -l encode-hide -d 'Modify the setting for the encode/decode auto-hide timer'
complete -c nvtop -s r -l reverse-abs -d 'Reverse abscissa: switch the plot data order from "old --- recent" (default) …'
complete -c nvtop -s p -l no-plot -d 'Show only one bar plot corresponding to the maximum of all GPUs'
complete -c nvtop -s v -l version -d 'Print the version and exit'

