# ompi_info
# Autogenerated from man page /usr/share/man/man1/ompi_info.1.gz
complete -c ompi_info -s a -l all -d parameters
complete -c ompi_info -l arch -d 'o 2'
complete -c ompi_info -s c -l config -d 'o 2'
complete -c ompi_info -o gmca -l gmca -d 'that are applicable to all contexts.  o 2'
complete -c ompi_info -s h -l help -d 'o 2'
complete -c ompi_info -l hostname -d 'and built.  o 2'
complete -c ompi_info -l internal -d 'modified by users).  o 2'
complete -c ompi_info -l level -d '(1-9).  The default is 1 unless --all is specified without'
complete -c ompi_info -o mca -l mca -d 'parameters; they are considered global if --gmca is not used and only one con…'
complete -c ompi_info -l param -d 'parameter is the type of the component to display; the second parameter is th…'
complete -c ompi_info -s t -l type -d parameter
complete -c ompi_info -l parsable -d 'output is displayed in a machine-parsable format --parseable Synonym for --pa…'
complete -c ompi_info -l path -d with
complete -c ompi_info -l pretty -d 'displayed in âprettyprintâ format (default) o 2'
complete -c ompi_info -l selected-only -d 'o 2'
complete -c ompi_info -s V -l version

