# oshmem_info
# Autogenerated from man page /usr/share/man/man1/oshmem_info.1.gz
complete -c oshmem_info -s a -l all -d 'o 2'
complete -c oshmem_info -l arch -d 'o 2'
complete -c oshmem_info -s c -l config -d 'o 2'
complete -c oshmem_info -o gmca -l gmca -d 'that are applicable to all contexts.  o 2'
complete -c oshmem_info -s h -l 'help*' -d 'o 2'
complete -c oshmem_info -l hostname -d 'and built on o 2'
complete -c oshmem_info -l internal -d 'modified by users) o 2'
complete -c oshmem_info -l level -d 'default is 1 unless --all is specified without --level in which case the defa…'
complete -c oshmem_info -o mca -l mca -d 'parameters; they are considered global if'
complete -c oshmem_info -l param -d 'parameter is the type of the component to display; the second parameter is th…'
complete -c oshmem_info -l parsable -d 'the output is displayed in a machine-parsable format --parseable Synonym for …'
complete -c oshmem_info -l path -d with
complete -c oshmem_info -l pretty -d 'output is displayed in prettyprint format (default) o 2'
complete -c oshmem_info -l selected-only -d 'o 2'
complete -c oshmem_info -s V -l 'version*'

