# oshmem-wrapper-compiler
# Autogenerated from man page /usr/share/man/man1/oshmem-wrapper-compiler.1.gz
complete -c oshmem-wrapper-compiler -l showme -d 'below)'
complete -c oshmem-wrapper-compiler -s v -d 'and -v.  o 2'
complete -c oshmem-wrapper-compiler -l showme:compile -d 'supplied to the underlying compiler.  o 2'
complete -c oshmem-wrapper-compiler -l showme:link -d 'supplied to the underlying compiler.  o 2'
complete -c oshmem-wrapper-compiler -l showme:command -d 'command (which may be one or more tokens).  o 2'
complete -c oshmem-wrapper-compiler -l showme:incdirs -d 'undecorated) list of directories that the wrapper compiler would have provide…'
complete -c oshmem-wrapper-compiler -l showme:libdirs -d 'undecorated) list of directories that the wrapper compiler would have provide…'
complete -c oshmem-wrapper-compiler -l showme:libs -d 'undecorated) list of library names that the wrapper compiler would have used …'
complete -c oshmem-wrapper-compiler -l showme:version -d 'o 2'
complete -c oshmem-wrapper-compiler -l showme:help -d 'See the man page for your underlying compiler for other options that can be p…'

