# pacconf
# Autogenerated from man page /usr/share/man/man1/pacconf.1.gz
complete -c pacconf -l config -d 'X Item "--config=path" Set an alternate configuration file path'
complete -c pacconf -l root -d 'X Item "--root=path" Set an alternate installation root'
complete -c pacconf -l sysroot -d 'X Item "--sysroot=path" Set an alternate system root'
complete -c pacconf -l arch -d 'X Item "--arch=arch" Set an alternate architecture'
complete -c pacconf -l null -d 'X Item "--null[=sep]" Set an alternate separator for values parsed from stdin'
complete -c pacconf -l options -d 'X Item "--options" Only display global settings from the \\f(CW\\*(C`[options]\\…'
complete -c pacconf -l raw -d 'X Item "--raw" Display unmodified values'
complete -c pacconf -l repo -d 'X Item "--repo=name" Only display directives for repository name'
complete -c pacconf -l repo-list -d 'X Item "--repo-list" List configured repositories'
complete -c pacconf -l single -d 'X Item "--single" Display only first value of multi-value options'
complete -c pacconf -l verbose -d 'X Item "--verbose" Always show directive names even if only one directive is …'
complete -c pacconf -l help -d 'X Item "--help" Display usage information and exit'
complete -c pacconf -l version

