# paccapability
# Autogenerated from man page /usr/share/man/man1/paccapability.1.gz
complete -c paccapability -l help -d 'X Item "--help" Display usage information and exit'
complete -c paccapability -l version

