# pacfile
# Autogenerated from man page /usr/share/man/man1/pacfile.1.gz
complete -c pacfile -l config -d 'X Item "--config=path" Set an alternate configuration file path'
complete -c pacfile -l dbpath -d 'X Item "--dbpath=path" Set an alternate database path'
complete -c pacfile -l root -d 'X Item "--root=path" Set an alternate installation root'
complete -c pacfile -l sysroot -d 'X Item "--sysroot=path" Set an alternate system root'
complete -c pacfile -l package -d 'X Item "--package=pkgname" Limit information to the specified package'
complete -c pacfile -l check -d 'X Item "--check" Compare database values to the file system'
complete -c pacfile -l help -d 'X Item "--help" Display usage information and exit'
complete -c pacfile -l version

