# pacinfo
# Autogenerated from man page /usr/share/man/man1/pacinfo.1.gz
complete -c pacinfo -l config -d 'X Item "--config=path" Set an alternate configuration file path'
complete -c pacinfo -l dbext -d 'X Item "--dbext=extension" Set an alternate sync database extension'
complete -c pacinfo -l dbpath -d 'X Item "--dbpath=path" Set an alternate database path'
complete -c pacinfo -l root -d 'X Item "--root=path" Set an alternate installation root'
complete -c pacinfo -l sysroot -d 'X Item "--sysroot=path" Set an alternate system root'
complete -c pacinfo -l null -d 'X Item "--null[=sep]" Set an alternate separator for values parsed from stdin'
complete -c pacinfo -l no-timeout -d 'X Item "--no-timeout" Disable low-speed timeouts for downloads'
complete -c pacinfo -l short -d 'X Item "--short" Display brief information'
complete -c pacinfo -l verbose -d 'X Item "--verbose" Display additional package information: \\f(CW\\*(C`required…'
complete -c pacinfo -l raw -d 'X Item "--raw" Display raw numeric size and date values'
complete -c pacinfo -l removable-size -d 'X Item "--removable-size" Include the size of any removable dependencies in i…'
complete -c pacinfo -l help -d 'X Item "--help" Display usage information and exit'
complete -c pacinfo -l version

