# pacini
# Autogenerated from man page /usr/share/man/man1/pacini.1.gz
complete -c pacini -l section -d 'X Item "--section=name" Only display directives listed in section name'
complete -c pacini -l section-list -d 'X Item "--section-list" List configured sections'
complete -c pacini -l verbose -d 'X Item "--verbose" Always show directive names even if only one directive is …'
complete -c pacini -l help -d 'X Item "--help" Display usage information and exit'
complete -c pacini -l version

