# paclog
# Autogenerated from man page /usr/share/man/man1/paclog.1.gz
complete -c paclog -l config -d 'X Item "--config=path" Set an alternate configuration file path'
complete -c paclog -l logfile -d 'X Item "--logfile=path" Set an alternate log file path'
complete -c paclog -l root -d 'X Item "--root=path" Set an alternate installation root'
complete -c paclog -l sysroot -d 'X Item "--sysroot=path" Set an alternate system root'
complete -c paclog -l color -d 'X Item "--[no-]color" Colorize output'
complete -c paclog -l pkglist -d 'X Item "--pkglist" Print the list of installed packages according to the log'
complete -c paclog -l help -d 'X Item "--help" Display usage information and exit'
complete -c paclog -l version -d 'X Item "--version" Display version information and exit'
complete -c paclog -l action -d 'X Item "--action=action" Display package operations'
complete -c paclog -l after -l before -d 'X Item "--after=date, --before=date" Display entries after/before date'
complete -c paclog -l caller -d 'X Item "--caller=name" Display log entries from name'
complete -c paclog -l commandline -d 'X Item "--commandline" Display pacman-style logged commandline entries'
complete -c paclog -l grep -d 'X Item "--grep=regex" Display log entries whose message matches regex'
complete -c paclog -l package -d 'X Item "--package=pkgname" Display logged actions affecting pkgname'
complete -c paclog -l warnings

