# paclock
# Autogenerated from man page /usr/share/man/man1/paclock.1.gz
complete -c paclock -l config -d 'X Item "--config=path" Set an alternate configuration file path'
complete -c paclock -l lockfile -d 'X Item "--lockfile=path" Set an alternate lock file path'
complete -c paclock -l root -d 'X Item "--root=path" Set an alternate installation root'
complete -c paclock -l sysroot -d 'X Item "--sysroot=path" Set an alternate system root'
complete -c paclock -l lock -d 'X Item "--lock" Lock the database (default)'
complete -c paclock -l unlock -d 'X Item "--unlock" Unlock the database'
complete -c paclock -l run -d 'X Item "--run" Treat \\f(CW\\*(C`argv\\*(C\' as a command to run with the databas…'
complete -c paclock -l fail-ok -d 'X Item "--fail-ok" Unlock the database after running a command with --run eve…'
complete -c paclock -l print -d 'X Item "--print" Write the lock file path to stdout and exit without modifyin…'
complete -c paclock -l no-check-keys -d 'X Item "--no-check-keys" Skip checking for an identity key match before unloc…'
complete -c paclock -l enoent-ok -d 'X Item "--enoent-ok" Do not treat a non-existent lock file as an error when u…'
complete -c paclock -l key -d 'X Item "--key=identity" An identifier to write to the lock file'
complete -c paclock -l help -d 'X Item "--help" Display usage information and exit'
complete -c paclock -l version

