# pacreport
# Autogenerated from man page /usr/share/man/man1/pacreport.1.gz
complete -c pacreport -l config -d 'X Item "--config=path" Set an alternate pacman configuration file path'
complete -c pacreport -l dbext -d 'X Item "--dbext=extension" Set an alternate sync database extension'
complete -c pacreport -l dbpath -d 'X Item "--dbpath=path" Set an alternate database path'
complete -c pacreport -l root -d 'X Item "--root=path" Set an alternate installation root'
complete -c pacreport -l sysroot -d 'X Item "--sysroot=path" Set an alternate system root'
complete -c pacreport -l cachedir -d 'X Item "--cachedir=path" Set an alternate cache directory path'
complete -c pacreport -l backups -d 'X Item "--backups" Search for . pac{save,orig,new} files'
complete -c pacreport -l group -d 'X Item "--group=name" Display any packages in group name that are not current…'
complete -c pacreport -l missing-files -d 'X Item "--missing-files" Check for missing package files'
complete -c pacreport -l unowned-files -d 'X Item "--unowned-files" Check for unowned files.   See /etc/pacreport'
complete -c pacreport -l optional-deps -d 'X Item "--optional-deps" Take optional dependencies into account when listing…'
complete -c pacreport -l help -d 'X Item "--help" Display usage information and exit'
complete -c pacreport -l version

