# pacrepairdb
# Autogenerated from man page /usr/share/man/man1/pacrepairdb.1.gz
complete -c pacrepairdb -l cachedir -d 'X Item "--cachedir=path" Set an alternate cache directory path'
complete -c pacrepairdb -l config -d 'X Item "--config=path" Set an alternate configuration file path'
complete -c pacrepairdb -l dbonly -d 'X Item "--dbonly" Make the changes to the database without actually extractin…'
complete -c pacrepairdb -l dbpath -d 'X Item "--dbpath=path" Set an alternate database path'
complete -c pacrepairdb -l debug -d 'X Item "--debug" Display additional debugging information'
complete -c pacrepairdb -l hookdir -d 'X Item "--hookdir" Add additional user hook directories'
complete -c pacrepairdb -l logfile -d 'X Item "--logfile=path" Set an alternate log file path'
complete -c pacrepairdb -l no-confirm -d 'X Item "--no-confirm" Assume default responses to all prompts'
complete -c pacrepairdb -l no-scriptlet -d 'X Item "--no-scriptlet" Do not run package install scripts'
complete -c pacrepairdb -l no-hooks -d 'X Item "--no-hooks" Do not run transaction hooks'
complete -c pacrepairdb -l no-timeout -d 'X Item "--no-timeout" Disable low-speed timeouts for downloads'
complete -c pacrepairdb -l print-only -d 'X Item "--print-only" Display the packages to be repaired and the cache packa…'
complete -c pacrepairdb -l root -d 'X Item "--root=path" Set an alternate installation root'
complete -c pacrepairdb -l sysroot -d 'X Item "--sysroot=path" Set an alternate system root'
complete -c pacrepairdb -l verbose -d 'X Item "--verbose" Display additional progress information'
complete -c pacrepairdb -l help -d 'X Item "--help" Display usage information and exit'
complete -c pacrepairdb -l version

