# pacrepairfile
# Autogenerated from man page /usr/share/man/man1/pacrepairfile.1.gz
complete -c pacrepairfile -l config -d 'X Item "--config=path" Set an alternate configuration file path'
complete -c pacrepairfile -l dbpath -d 'X Item "--dbpath=path" Set an alternate database path'
complete -c pacrepairfile -l root -d 'X Item "--root=path" Set an alternate installation root'
complete -c pacrepairfile -l sysroot -d 'X Item "--sysroot=path" Set an alternate system root'
complete -c pacrepairfile -l quiet -d 'X Item "--quiet" Do not display progress information'
complete -c pacrepairfile -l package -d 'X Item "--package=pkgname" Search pkgname for file properties'
complete -c pacrepairfile -l help -d 'X Item "--help" Display usage information and exit'
complete -c pacrepairfile -l version -d 'X Item "--version" Display version information and exit'
complete -c pacrepairfile -l gid -d 'X Item "--gid" Reset file owner group id'
complete -c pacrepairfile -l mode -d 'X Item "--mode" Reset file permissions'
complete -c pacrepairfile -l mtime -d 'X Item "--mtime" Reset file modification time'
complete -c pacrepairfile -l uid

