# pacsync
# Autogenerated from man page /usr/share/man/man1/pacsync.1.gz
complete -c pacsync -l config -d 'X Item "--config=path" Set an alternate configuration file path'
complete -c pacsync -l dbext -d 'X Item "--dbext=extension" Set an alternate sync database extension'
complete -c pacsync -l dbpath -d 'X Item "--dbpath=path" Set an alternate database path'
complete -c pacsync -l logfile -d 'X Item "--logfile=path" Set an alternate log file path'
complete -c pacsync -l no-timeout -d 'X Item "--no-timeout" Disable low-speed timeouts for downloads'
complete -c pacsync -l root -d 'X Item "--root=path" Set an alternate installation root'
complete -c pacsync -l sysroot -d 'X Item "--sysroot=path" Set an alternate system root'
complete -c pacsync -l debug -d 'X Item "--debug" Display additional debugging information'
complete -c pacsync -l updated -d 'X Item "--updated" Return true only if a database was actually updated'
complete -c pacsync -l force -d 'X Item "--force" Update databases even if already up-to-date'
complete -c pacsync -l help -d 'X Item "--help" Display usage information and exit'
complete -c pacsync -l version

