# parcat
# Autogenerated from man page /usr/share/man/man1/parcat.1.gz
complete -c parcat -s '#' -d 'X Item "-#" Arguments following this will be sent to the file descriptor #'
complete -c parcat -l rm

