# pldd
# Autogenerated from man page /usr/share/man/man1/pldd.1.gz
complete -c pldd -l help -d 'TQ  -? Display a help message and exit'
complete -c pldd -l usage -d 'Display a short usage message and exit'
complete -c pldd -s '?' -d 'Display a help message and exit'
complete -c pldd -l version
complete -c pldd -s V -d 'Display program version information and exit'

