# pmix_info
# Autogenerated from man page /usr/share/man/man1/pmix_info.1.gz
complete -c pmix_info -s h -l help -d 'argument is not provided, then a generalized help message similar to the info…'
complete -c pmix_info -s v -l verbose -d 'o 2'
complete -c pmix_info -s V -l version -d 'o 2'
complete -c pmix_info -s a -l all -d 'parameters.  o 2'
complete -c pmix_info -l arch -d 'o 2'
complete -c pmix_info -s c -l config -d 'o 2'
complete -c pmix_info -l hostname -d 'and built.  o 2'
complete -c pmix_info -l internal -d 'modified by users).  o 2'
complete -c pmix_info -l param -d 'parameter is the framework (or the keyword âallâ); the second parameter i…'
complete -c pmix_info -l path -d with
complete -c pmix_info -l pretty-print -d 'displayed in âprettyprintâ format (default) o 2'
complete -c pmix_info -l parsable -d 'displayed in a machine-parsable format o 2'
complete -c pmix_info -l parseable -d 'o 2'
complete -c pmix_info -l show-failed -d 'o 2'
complete -c pmix_info -l selected-only

