# sem
# Autogenerated from man page /usr/share/man/man1/sem.1.gz
complete -c sem -l bg -d 'X Item "--bg" Run command in background thus GNU sem will not wait for comple…'
complete -c sem -l jobs -d 'X Item "--jobs N"'
complete -c sem -s j -d 'X Item "-j N"'
complete -c sem -l max-procs -d 'X Item "--max-procs N"'
complete -c sem -s P -d 'X Item "-P N" . PD Run up to N commands in parallel'
complete -c sem -s N -d 'X Item "--jobs -N"'
complete -c sem -l pipe -d 'X Item "--pipe" Pass stdin (standard input) to command'
complete -c sem -l semaphorename -d 'X Item "--semaphorename name"'
complete -c sem -l id -d 'X Item "--id name" . PD Use name as the name of the semaphore'
complete -c sem -l fg -d 'X Item "--fg" Do not put command in background'
complete -c sem -l semaphoretimeout -d 'X Item "--semaphoretimeout secs"'
complete -c sem -l st -d 'X Item "--st secs" '
complete -c sem -l wait

