# showttf
# Autogenerated from man page /usr/share/man/man1/showttf.1.gz
complete -c showttf -l verbose -s v -d 'Print additional information'
complete -c showttf -l headers -s h -d 'Print headers only'
complete -c showttf -l checkhead -s c -d 'Check Head SEE ALSO fontforge(1) acorn2sfd(1) ttf2eps(1) AUTHORS showttf was …'

