# sign-efi-sig-list
# Autogenerated from man page /usr/share/man/man1/sign-efi-sig-list.1.gz
complete -c sign-efi-sig-list -s r -d 'the certificate is rsa2048 rather than x509 [UNIMPLEMENTED]'
complete -c sign-efi-sig-list -s m -d 'Use a monotonic count instead of a timestamp [UNIMPLEMENTED]'
complete -c sign-efi-sig-list -s a -d 'Prepare the variable for APPEND_WRITE rather than replacement'
complete -c sign-efi-sig-list -s o -d 'Do not sign, but output a file of the exact bundle to be signed'
complete -c sign-efi-sig-list -s t -d 'Use <timestamp> as the timestamp of the timed variable update If not present,…'
complete -c sign-efi-sig-list -s i -d 'take a detached signature (in PEM format) of the bundle produced by -o and co…'
complete -c sign-efi-sig-list -s g -d 'Use <guid> as the signature owner GUID'
complete -c sign-efi-sig-list -s c -d '<crt> is the file containing the signing certificate in PEM format'
complete -c sign-efi-sig-list -s k -d '<key> is the file containing the key for <crt> in PEM format'
complete -c sign-efi-sig-list -s e -d 'Use openssl engine <engine> for the private key EXAMPLES'

