# sprof
# Autogenerated from man page /usr/share/man/man1/sprof.1.gz
complete -c sprof -l call-pairs -d 'TQ  -c Print a list of pairs of call paths for the interfaces exported by the…'
complete -c sprof -l flat-profile -d 'TQ  -p Generate a flat profile of all of the functions in the monitored objec…'
complete -c sprof -l graph -d 'TQ  -q Generate a call graph'
complete -c sprof -l help -d 'TQ  -? Display a summary of command-line options and arguments and exit'
complete -c sprof -l usage -d 'Display a short usage message and exit'
complete -c sprof -s c -d 'Print a list of pairs of call paths for the interfaces exported by the shared…'
complete -c sprof -s p -d 'Generate a flat profile of all of the functions in the monitored object, with…'
complete -c sprof -s q -d 'Generate a call graph'
complete -c sprof -s '?' -d 'Display a summary of command-line options and arguments and exit'
complete -c sprof -l version
complete -c sprof -s V -d 'Display the program version and exit.  STANDARDS GNU'
complete -c sprof -l --------------------------------------------- -d '                0. 00    0. 00        1/1           <UNKNOWN> [1]      0'

