# sql
# Autogenerated from man page /usr/share/man/man1/sql.1.gz
complete -c sql -l csv
complete -c sql -l db-size
complete -c sql -l dbsize -d 'Size of database.  Show the size of the database on disk'
complete -c sql -l help
complete -c sql -s h -d 'Print a summary of the options to GNU sql and exit'
complete -c sql -l html
complete -c sql -l json
complete -c sql -l pretty -d 'Pretty JSON output'
complete -c sql -l list-databases
complete -c sql -l listdbs
complete -c sql -l show-databases
complete -c sql -l showdbs -d 'List the databases (table spaces) in the database'
complete -c sql -l listproc
complete -c sql -l proclist
complete -c sql -l show-processlist -d 'Show the list of running queries'
complete -c sql -l list-tables
complete -c sql -l show-tables
complete -c sql -l table-list -d 'List the tables in the database'
complete -c sql -l noheaders
complete -c sql -l no-headers
complete -c sql -s n -d 'Remove headers and footers and print only tuples'
complete -c sql -s p
complete -c sql -s U -s U
complete -c sql -l precision
complete -c sql -s r
complete -c sql -l retries
complete -c sql -l sep
complete -c sql -s s -d 'Field separator.  Use string as separator between columns'
complete -c sql -l skip-first-line
complete -c sql -l table-size
complete -c sql -l tablesize -d 'Size of tables.  Show the size of the tables in the database'
complete -c sql -l verbose
complete -c sql -s v -d 'Print which command is sent'
complete -c sql -l version
complete -c sql -s V -d 'Print the version GNU sql and exit'
complete -c sql -l shebang
complete -c sql -s Y -d 'GNU sql can be called as a shebang (#!) command as the first line of a script'

