# swaync
# Autogenerated from man page /usr/share/man/man1/swaync.1.gz
complete -c swaync -s v -l version -d 'Prints version'
complete -c swaync -s s -l style -d 'Use a custom Stylesheet file'
complete -c swaync -s c -l config -d 'Use a custom config file'

