# swaync-client
# Autogenerated from man page /usr/share/man/man1/swaync-client.1.gz
complete -c swaync-client -s h -l help
complete -c swaync-client -s v -l version
complete -c swaync-client -s R -l reload-config
complete -c swaync-client -o rs -l reload-css
complete -c swaync-client -s t -l toggle-panel
complete -c swaync-client -o op -l open-panel
complete -c swaync-client -o cp -l close-panel
complete -c swaync-client -s d -l toggle-dnd
complete -c swaync-client -s D -l get-dnd
complete -c swaync-client -o dn -l dnd-on
complete -c swaync-client -o df -l dnd-off
complete -c swaync-client -s I -l get-inhibited
complete -c swaync-client -o In -l get-num-inhibitors
complete -c swaync-client -o Ia -l inhibitor-add
complete -c swaync-client -o Ir -l inhibitor-remove
complete -c swaync-client -o Ic -l inhibitors-clear
complete -c swaync-client -s c -l count
complete -c swaync-client -l hide-latest
complete -c swaync-client -l close-latest
complete -c swaync-client -s C -l close-all
complete -c swaync-client -o sw -l skip-wait
complete -c swaync-client -s s -l subscribe
complete -c swaync-client -o swb -l subscribe-waybar

