# swww-daemon
# Autogenerated from man page /usr/share/man/man1/swww-daemon.1.gz
complete -c swww-daemon -l no-cache -d 'Don\'t search the cache for the last wallpaper for each output'
complete -c swww-daemon -s q -l quiet -d 'Makes the daemon only log errors'
complete -c swww-daemon -s h -l help -d 'Print help (see a summary with \'-h\')'
complete -c swww-daemon -s V -l version -d 'Print version'

