# swww-init
# Autogenerated from man page /usr/share/man/man1/swww-init.1.gz
complete -c swww-init -l no-cache -d 'Don\'t load the cache during initialization (it still loads on monitor'
complete -c swww-init -l format -d 'Force the daemon to use a specific wl_shm format'
complete -c swww-init -s h -l help -d 'Print help (see a summary with \'-h\')'

