# ttx
# Autogenerated from man page /usr/share/man/man1/ttx.1.gz
complete -c ttx -s h -d 'Display usage information'
complete -c ttx -s d -d 'Write the output files to directory dir instead of writing every output file …'
complete -c ttx -s o -d 'Write the output to file instead of writing it to the same directory as the c…'
complete -c ttx -s v -d 'Be verbose'
complete -c ttx -s a -d 'Allow virtual glyphs ID\'s on compile or decompile'
complete -c ttx -s l -d 'List table information'
complete -c ttx -s t -d 'Dump table table'
complete -c ttx -s x -d 'Exclude table table from the list of tables to dump'
complete -c ttx -s s -d 'Split tables'
complete -c ttx -s i -d 'Don\'t disassemble TrueType instructions'
complete -c ttx -s y -d 'When decompiling a TrueType Collection (TTC) file, decompile font number n, s…'
complete -c ttx -s m -d 'Merge the input TTX file file with fontfile'
complete -c ttx -s b -d 'Don\'t recalculate glyph bounding boxes'

