# wallust-theme
# Autogenerated from man page /usr/share/man/man1/wallust-theme.1.gz
complete -c wallust-theme -s p -l preview -d 'Only preview the selected theme'
complete -c wallust-theme -s h -l help -d 'Print help'

