# wallust
# Autogenerated from man page /usr/share/man/man1/wallust.1.gz
complete -c wallust -s i -l ignore-sequence -d 'Won\\*(Aqt send these colors sequences . br  '
complete -c wallust -s q -l quiet -d 'Don\\*(Aqt print anything'
complete -c wallust -s s -l skip-sequences -d 'Skip setting terminal sequences'
complete -c wallust -s T -l skip-templates -d 'Skip templating process'
complete -c wallust -s u -l update-current -d 'Only update the current terminal'
complete -c wallust -s C -l config-file -d 'Use FILE as the config file'
complete -c wallust -s d -l config-dir -d 'Uses DIR as the config directory, which holds both `wallust'
complete -c wallust -s N -l no-config -d 'Uses DIR as the config directory, which holds both `wallust'
complete -c wallust -s h -l help -d 'Print help (see a summary with \\*(Aq-h\\*(Aq)'
complete -c wallust -s V -l version -d 'Print version'

