# wallust-cs
# Autogenerated from man page /usr/share/man/man1/wallust-cs.1.gz
complete -c wallust-cs -s f -l format -d 'Specify a custom format'
complete -c wallust-cs -s h -l help -d 'Print help (see a summary with \\*(Aq-h\\*(Aq)'

