# wifi-menu
# Autogenerated from man page /usr/share/man/man1/wifi-menu.1.gz
complete -c wifi-menu -s h -l help -d 'Print a short help text and exit'
complete -c wifi-menu -s o -l obscure -d 'Show asterisks for the characters of the password and store the password as a…'

