# x86_64-w64-mingw32-size
# Autogenerated from man page /usr/share/man/man1/x86_64-w64-mingw32-size.1.gz
complete -c x86_64-w64-mingw32-size -s A -d 'X Item "-A"'
complete -c x86_64-w64-mingw32-size -s B -d 'X Item "-B"'
complete -c x86_64-w64-mingw32-size -s G -d 'X Item "-G"'
complete -c x86_64-w64-mingw32-size -l format -d 'X Item "--format=compatibility" '
complete -c x86_64-w64-mingw32-size -l help -d 'X Item "--help" Show a summary of acceptable arguments and options'
complete -c x86_64-w64-mingw32-size -s d -d 'X Item "-d"'
complete -c x86_64-w64-mingw32-size -s o -d 'X Item "-o"'
complete -c x86_64-w64-mingw32-size -s x -d 'X Item "-x"'
complete -c x86_64-w64-mingw32-size -l radix -d 'X Item "--radix=number" '
complete -c x86_64-w64-mingw32-size -l common -d 'X Item "--common" Print total size of common symbols in each file'
complete -c x86_64-w64-mingw32-size -s t -d 'X Item "-t"'
complete -c x86_64-w64-mingw32-size -l totals -d 'X Item "--totals" '
complete -c x86_64-w64-mingw32-size -l target -d 'X Item "--target=bfdname" Specify that the object-code format for objfile is …'
complete -c x86_64-w64-mingw32-size -s V -d 'X Item "-V"'
complete -c x86_64-w64-mingw32-size -l version -d 'X Item "--version" . PD Display the version number of size'

