# xcur2png
# Autogenerated from man page /usr/share/man/man1/xcur2png.1.gz
complete -c xcur2png -s V -l version -d 'Display the version number and exit with status 0'
complete -c xcur2png -s h -l help -d 'Display the usage message and exit with status 0'
complete -c xcur2png -s c -l conf -d 'Set output path of config-file.  If "-" is specified, stdout(3) is used'
complete -c xcur2png -s d -l directory -d 'Set the path of a directory which PNG images are saved in'
complete -c xcur2png -s i -l initial-suffix -d 'Set the initial suffix of PNG images to suffix'
complete -c xcur2png -s q -l quiet -d 'Suppress progress message'
complete -c xcur2png -s n -l dry-run -d 'Do not output PNG images and config-data to files'

