# xfs_mdrestore
# Autogenerated from man page /usr/share/man/man8/xfs_mdrestore.8.gz
complete -c xfs_mdrestore -s g -d 'Shows restore progress on stdout'
complete -c xfs_mdrestore -s i -d 'Shows metadump information on stdout'
complete -c xfs_mdrestore -s l -d 'Metadump in v2 format can contain metadata dumped from an external log'
complete -c xfs_mdrestore -s V -d 'Prints the version number and exits'

